### ISSUE TITLE
Regarding Plugins

### ISSUE THREAD

**Issue by coding-sunshine** [leung0826/Adminer-for-laravel#10]
Just wanted to know how can I add plugins to this?

**Comment by Artistan** [comment]
go into your project `/vendors/leung0826/adminer-for-larave/resources/`
I believe that is the standard place to install plugins for adminer?

**Comment by coding-sunshine** [comment]
Okies, Let me try this. Maybe if you want I can keep pull request for some plugins soon?

**Comment by Artistan** [comment]
that would be great.
