### ISSUE TITLE
Adminer Not Found

### ISSUE THREAD

**Issue by yoesoff** [leung0826/Adminer-for-laravel#11]
Hi just installed you package and adminer.php cannot be found in the package's folder  ?

**Comment by lhq0826** [comment]
@yoesoff What is your laravel version? adminer.php usually under the src/resources directory.

**Comment by mosinve** [comment]
Issue because of Adminer update method search 'name' field in releases/latest json
but currenlty it's   `"name": "",`  so it can't define needed version to download

**Comment by mosinve** [comment]
as a quick fix, i suggest to lookup ` "tag_name": "v4.6.2",` field instead
