### ISSUE TITLE
v4.3.1 is out

### ISSUE THREAD

**Issue by Artistan** [leung0826/Adminer-for-laravel#4]
have you tried to get composer include adminer?
thanks!

**Comment by leung0826** [comment]
Hi, the next version.

**Comment by lhq0826** [comment]
@Artistan Hi, the next version

**Comment by Artistan** [comment]
Yep, you want me to do a pull request for ya?

**Comment by Artistan** [comment]
https://github.com/leung0826/adminer-for-laravel/pull/5
this handles the issue and automates it for the future.

**Comment by Artistan** [comment]
Can you just add me as a collaborator / maintainer?
I would like to keep updating this rather than fork my own version.

**Comment by leung0826** [comment]
@Artistan ok

**Comment by lhq0826** [comment]
@Artistan Welcome,I'm  looking   forward   to  cooperating.
